name: yoga
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+47

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^9.3.0
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^4.17.5
  flutter_spinkit: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  wakelock_plus: ^1.2.5
  google_fonts: ^6.2.1
  volume_control: ^0.1.5
  showcaseview: ^3.0.0
  flutter_local_notifications: ^17.1.2
  package_info_plus: ^8.0.0
  workmanager: ^0.5.0
  url_launcher: ^6.0.9
  fl_chart: ^0.68.0
  drag_and_drop_lists: ^0.3.2
  upgrader: ^10.3.0
  local_auth: ^2.1.2
  share_plus: ^9.0.0
  #video_player: ^2.4.7
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/yoga_icon_circular.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/audio/yoga.mp3
     - assets/images/
     - assets/icon/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
